# config settings the user is allowed to tweak
spae:
  args:
    # args
  params:
    medaka: "r941_min_sup_g507"
    flye: "--nano-hq"


trimnami:
    qc:
        subsample:
            --num 1m


resources:
  smalljob:
    cpu: 8
    mem: 16000
    time: 480
  bigjob:
    cpu: 32
    mem: 64000
    time: 480



 